import Navbar from './navbar'
import Footer from './footer'
import Head from "next/head";
import {Alert} from "antd";

export default function Layout({children}) {
    return (
        <>
            <Head>
                <title>ALPS Mart</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
                <script async id="ze-snippet" src="https://static.zdassets.com/ekr/snippet.js?key=bd92b888-8b41-4e3a-ba8b-9310dc8a72c0"> </script>
            </Head>
            <Alert
                banner
                message="COVID-19 UPDATE: Our dispatching center is fully operating. PLEASE EXPECT DELAY due to our courier partners are experiencing high volumes. Pickup Center remains closed under alert level 3."
            />
            <section style={{maxWidth: '1170px', margin: '0 auto'}}>
                <Navbar/>
                <main>{children}</main>
            </section>
            <Footer/>

        </>
    )
}
